model:
  name: "meta-llama/Llama-2-7b-hf"
  vision_model_name: "openai/clip-vit-large-patch14"
  max_seq_length: 512
  max_image_resolution: [224, 224]

training:
  method: "vision_supervised_fine_tuning"
  learning_rate: 2e-5
  batch_size: 8
  num_epochs: 3
  gradient_accumulation_steps: 1
  warmup_steps: 500
  weight_decay: 0.01
  logging_steps: 100
  eval_steps: 500
  save_steps: 1000
  output_dir: "./output/vision_sft"
  seed: 42
  mixed_precision: true
  distributed_training: false
  num_gpus: 1
  use_cpp_extension: false
  
  # VisionSFT specific
  vision_backbone: "clip"
  lora_r: 16
  lora_alpha: 32
  lora_dropout: 0.05
  use_lora: true
  use_8bit_quantization: false
  adapter_mode: "parallel"
  loss_type: "token"
  image_augmentation: true
  augmentation_strength: 0.5

data:
  train_file: "./data/train.jsonl"
  eval_file: "./data/eval.jsonl"
  image_dir: "./data/images"

use_wandb: false
wandb:
  project: "open-vlm"
  run_name: "vision-sft-run-1" 